<a href="https://colab.research.google.com/github/anindya2001/GraphSemanticSegmentation/blob/main/EvSegNet_Dataset_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
np.load('/content/drive/MyDrive/EVSEGNET DATASET SAMPLES/Others/rec1487782014_export_3843.npy')

array([[[-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-0.88235295, -1.        , -0.23672   ,  0.        ,
          0.        ,  0.        ],
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        ...,
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        ...,
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
  

In [15]:
import numpy as np
np.load('/content/drive/MyDrive/EVSEGNET DATASET SAMPLES/Train Samples/rec1487593224_export_889.npy')

array([[[-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-0.71428573, -1.        , -0.9734    ,  0.        ,
          0.        ,  0.        ],
        [-0.71428573,  0.        , -0.59472   ,  0.        ,
          0.31057334,  0.30147818],
        ...,
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-0.71428573, -0.3333333 , -0.8292    ,  0.        ,
          0.81284   ,  0.08688   ],
        ...,
        [-1.        , -1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
  

In [16]:
import numpy as np
np.load('/content/drive/MyDrive/EVSEGNET DATASET SAMPLES/Test samples/rec1487417411_export_333.npy')

array([[[-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        ...,
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.]],

       [[-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        ...,
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.]],

       [[-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        ...,
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.]],

       ...,

       [[-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        ...,
        [-1., -1.,  0.,  0.,  0.,  0.],
        [-1., -1.,  0.,  0.,  0.,  0.],
        [