In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
ls '/content/drive/MyDrive/hdf5/outdoor_day'

outdoor_day1_data.hdf5  outdoor_day2_data.hdf5  outdoor_day_calib.zip
outdoor_day1_gt.hdf5    outdoor_day2_gt.hdf5


In [3]:
import h5py

file_name = "/content/drive/MyDrive/hdf5/outdoor_day/outdoor_day1_data.hdf5"

f = h5py.File(file_name, "r")
for key in f.keys():
    print(key) #Names of the groups in HDF5 file.

davis
velodyne
visensor


In [4]:
#Get the HDF5 group
group = f['davis']

#Checkout what keys are inside that group.
for key in group.keys():
    print(key)

left
right


In [5]:
subgroup = group['left']
subgroup['events'][6]

array([2.7000000e+01, 4.7000000e+01, 1.5061179e+09, 1.0000000e+00])

In [6]:
subgroup = group['left']
subgroup['events']

<HDF5 dataset "events": shape (105874257, 4), type "<f8">

In [9]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [7]:
print(subgroup['events'].value)

[[ 1.43000000e+02  5.40000000e+01  1.50611790e+09  1.00000000e+00]
 [ 3.00000000e+00  1.29000000e+02  1.50611790e+09 -1.00000000e+00]
 [ 1.06000000e+02  5.30000000e+01  1.50611790e+09  1.00000000e+00]
 ...
 [ 5.00000000e+01  8.70000000e+01  1.50611816e+09  1.00000000e+00]
 [ 6.90000000e+01  1.24000000e+02  1.50611816e+09 -1.00000000e+00]
 [ 3.19000000e+02  4.20000000e+01  1.50611816e+09  1.00000000e+00]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  """Entry point for launching an IPython kernel.


In [8]:
print(subgroup['image_raw'].value)

[[[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ... 10  4  1]
  [ 0  0  0 ... 30 25 20]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ... 15  5  2]
  [ 0  0  0 ... 31 24 20]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ... 16  7  1]
  [ 0  0  0 ... 29 26 18]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 ...

 [[ 0  0  0 ... 25 11  6]
  [ 0  0  0 ... 51 30 19]
  [ 0  0  0 ... 64 46 36]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[ 0  0  0 ... 26 14  3]
  [ 0  0  0 ... 48 28 19]
  [ 0  0  0 ... 65 46 41]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[ 0  0  0 ... 25 12  1]
  [ 0  0  0 ... 44 27 21]
  [ 0  0  0 ... 68 48 38]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  """Entry point for launching an IPython kernel.


In [9]:
print(subgroup['image_raw_ts'].value)

[1.50611790e+09 1.50611790e+09 1.50611790e+09 ... 1.50611816e+09
 1.50611816e+09 1.50611816e+09]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  """Entry point for launching an IPython kernel.
